import type { Metadata } from 'next';
import { IBM_Plex_Mono, Special_Elite } from 'next/font/google';
import './globals.css';

const bodyFont = IBM_Plex_Mono({
	variable: '--font-body',
	weight: ['400', '500', '600'],
	subsets: ['latin'],
});

const headingFont = Special_Elite({
	variable: '--font-heading',
	weight: '400',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl-PL'>
			<body
				className={`${bodyFont.variable} ${headingFont.variable} antialiased`}
			>
				<div className='min-h-screen w-full relative'>
					<div
						className='absolute inset-0 z-0'
						style={{
							backgroundColor: '#0a0a0a',
							backgroundImage: `
				 radial-gradient(circle at 25% 25%, #222222 0.5px, transparent 1px),
				 radial-gradient(circle at 75% 75%, #111111 0.5px, transparent 1px)
			 `,
							backgroundSize: '10px 10px',
							imageRendering: 'pixelated',
						}}
					/>
					<div className='relative z-10'>{children}</div>
				</div>
			</body>
		</html>
	);
}
